# Basic set up for three package managers

version: 2
updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - "martins.vds"
    labels:
      - "nuget dependencies".
      
  # Maintain dependencies for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - "martins.vds"
    labels:
      - "npm dependencies"
