# Basic set up for three package managers

version: 2
updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - "martins-vds"
  # Maintain dependencies for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - "martins-vds"

  # Maintain dependencies for Composer
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - "martins-vds"
