name: Deployment

on:
  pull_request:
    types:
      - closed

jobs:
  extract-env-name:
    runs-on: ubuntu-latest
    steps:
      - name: Extract Environment Name
        env:
          PR_HEAD: ${{ github.base_ref }}
        run: echo "##[set-output name=environment;]$(echo ${PR_HEAD#refs/heads/} | tr / -)"

  deploy-to-qa:
    needs: extract-env-name
    runs-on: ubuntu-latest
    if: ${{ contains(needs.extract-env-name.outputs.environment, 'qa') }}
    steps:
    - name: Start deployment
      uses: bobheadxi/deployments@master
      id: qa_deployment
      with:
        step: start
        token: ${{ secrets.GITHUB_TOKEN }}
        env: QA
    - name: Deploy to QA 
      run: |
        echo "Deploying to QA"
    - name: Update deployment status
      uses: bobheadxi/deployments@master
      if: always()
      with:
        step: finish
        token: ${{ secrets.GITHUB_TOKEN }}
        status: ${{ job.status }}
        deployment_id: ${{ steps.qa_deployment.outputs.deployment_id }}   
  
