name: Deployment

on:
  pull_request:
    types:
      - closed

jobs:
  deploy-to-qa:
    runs-on: ubuntu-latest
    if: contains(github.base_ref, 'refs/heads/qa')
    steps:
    - name: Start deployment
      uses: bobheadxi/deployments@master
      id: qa_deployment
      with:
        step: start
        token: ${{ secrets.GITHUB_TOKEN }}
        env: QA
    - name: Deploy to QA 
      run: |
        echo "Deploying to QA"
    - name: Update deployment status
      uses: bobheadxi/deployments@master
      if: always()
      with:
        step: finish
        token: ${{ secrets.GITHUB_TOKEN }}
        status: ${{ job.status }}
        deployment_id: ${{ steps.qa_deployment.outputs.deployment_id }}   
  
