name: eShopOnWeb Build and Test

on:
  push:
    branches:
      - master
      - dev
    paths-ignore:
      - '.github/**'
  pull_request:
    branches: [master, qa, prod]
  workflow_dispatch:

jobs:
  build:
    name: eShopOnWeb - Build and Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.201
    - name: Setup Report Generator Tool
      run: dotnet tool install --global dotnet-reportgenerator-globaltool
    - name: Build with dotnet
      run: dotnet build ./eShopOnWeb.sln --configuration Release
    - name: Test with dotnet
      run: dotnet test ./eShopOnWeb.sln --configuration Release --collect:"XPlat code coverage"
    - name: Generate Code Coverage Report
      run: reportgenerator "-reports:tests\*\*\*\coverage.cobertura.xml" "-targetdir:coverage-reports"
    - name: Update Code Coverage Report
      uses: actions/upload-artifact@master
      with:
          name: Coverage
          path: coverage-reports