name: Semantic Versioning

on: workflow_dispatch

jobs:
    calculate-sem-ver:
      runs-on: windows-latest
      steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Fetch all history for all tags and branches
        run: git fetch --prune --unshallow
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.4
        with:
            versionSpec: '5.2.x'
      - name: Use GitVersion
        id: gitversion # step id used as reference for output values
        uses: gittools/actions/gitversion/execute@v0.9.4
        with:
            updateAssemblyInfo: true
      - run: |
          Write-Host "Major: ${{ steps.gitversion.outputs.major }}"
          Write-Host "Minor: ${{ steps.gitversion.outputs.minor }}"
          Write-Host "Patch: ${{ steps.gitversion.outputs.patch }}"
          Write-Host "PreReleaseTag: ${{ steps.gitversion.outputs.preReleaseTag }}"
          Write-Host "PreReleaseTagWithDash: ${{ steps.gitversion.outputs.preReleaseTagWithDash }}"
          Write-Host "PreReleaseLabel: ${{ steps.gitversion.outputs.preReleaseLabel }}"
          Write-Host "PreReleaseNumber: ${{ steps.gitversion.outputs.preReleaseNumber }}"
          Write-Host "WeightedPreReleaseNumber: ${{ steps.gitversion.outputs.weightedPreReleaseNumber }}"
          Write-Host "BuildMetaData: ${{ steps.gitversion.outputs.buildMetaData }}"
          Write-Host "BuildMetaDataPadded: ${{ steps.gitversion.outputs.buildMetaDataPadded }}"
          Write-Host "FullBuildMetaData: ${{ steps.gitversion.outputs.fullBuildMetaData }}"
          Write-Host "MajorMinorPatch: ${{ steps.gitversion.outputs.majorMinorPatch }}"
          Write-Host "SemVer: ${{ steps.gitversion.outputs.semVer }}"
          Write-Host "LegacySemVer: ${{ steps.gitversion.outputs.legacySemVer }}"
          Write-Host "LegacySemVerPadded: ${{ steps.gitversion.outputs.legacySemVerPadded }}"
          Write-Host "AssemblySemVer: ${{ steps.gitversion.outputs.assemblySemVer }}"
          Write-Host "AssemblySemFileVer: ${{ steps.gitversion.outputs.assemblySemFileVer }}"
          Write-Host "FullSemVer: ${{ steps.gitversion.outputs.fullSemVer }}"
          Write-Host "InformationalVersion: ${{ steps.gitversion.outputs.informationalVersion }}"
          Write-Host "BranchName: ${{ steps.gitversion.outputs.branchName }}"
          Write-Host "Sha: ${{ steps.gitversion.outputs.sha }}"
          Write-Host "ShortSha: ${{ steps.gitversion.outputs.shortSha }}"
          Write-Host "NuGetVersionV2: ${{ steps.gitversion.outputs.nuGetVersionV2 }}"
          Write-Host "NuGetVersion: ${{ steps.gitversion.outputs.nuGetVersion }}"
          Write-Host "NuGetPreReleaseTagV2: ${{ steps.gitversion.outputs.nuGetPreReleaseTagV2 }}"
          Write-Host "NuGetPreReleaseTag: ${{ steps.gitversion.outputs.nuGetPreReleaseTag }}"
          Write-Host "VersionSourceSha: ${{ steps.gitversion.outputs.versionSourceSha }}"
          Write-Host "CommitsSinceVersionSource: ${{ steps.gitversion.outputs.commitsSinceVersionSource }}"
          Write-Host "CommitsSinceVersionSourcePadded: ${{ steps.gitversion.outputs.commitsSinceVersionSourcePadded }}"
          Write-Host "CommitDate: ${{ steps.gitversion.outputs.commitDate }}"